title: elexis-austria
description: elexis-austria ist eine einzigartige freie Software für niedergelassene Wahlärzte in Österreich
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
baseurl: /elexis-austria
